import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { cookies } from 'next/headers'
import LogoutButton from "@/components/logoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const session = cookieStore.get('session')
  const user = session ? JSON.parse(session.value) : null

  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="bg-gray-800 text-white p-4">
          <div className="container mx-auto flex justify-between">
            <div className="flex gap-6">
              <Link 
                href="/" 
                className="hover:text-gray-300 transition-colors"
              >
                Accueil
              </Link>
              <Link 
                href="/about" 
                className="hover:text-gray-300 transition-colors"
              >
                À propos
              </Link>
              <Link 
                href="/contact" 
                className="hover:text-gray-300 transition-colors"
              >
                Contact
              </Link>
              <Link 
                href="/coffee" 
                className="hover:text-gray-300 transition-colors"
              >
                Nos Cafés
              </Link>
              <Link 
                href="/beers" 
                className="hover:text-gray-300 transition-colors"
              >
                Nos Bières
              </Link>
              <Link 
                href="/blog" 
                className="hover:text-gray-300 transition-colors"
              >
                Blog
              </Link>
            </div>

            <div className="flex gap-4 items-center">
              {user ? (
                <>
                  <Link 
                    href="/admin" 
                    className="hover:text-gray-300 transition-colors"
                  >
                    Admin
                  </Link>
                  <span className="text-gray-400">
                    {user.username}
                  </span>
                  <LogoutButton />
                </>
              ) : (
                <>
                  <Link 
                    href="/login"
                    className="hover:text-gray-300 transition-colors"
                  >
                    Connexion
                  </Link>
                  <Link 
                    href="/register"
                    className="bg-blue-600 hover:bg-blue-700 px-3 py-1 rounded-md transition-colors"
                  >
                    S&apos;inscrire
                  </Link>
                </>
              )}
            </div>
          </div>
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
